# Strategy Configuration
# Configuration for different trading strategies

qullamaggie:
  description: "Momentum breakout strategy based on Qullamaggie's methods"
  
  # Strategy parameters
  parameters:
    min_market_cap: 1000000000      # $1B minimum
    min_avg_volume: 1000000         # 1M shares
    max_price: 200                  # Maximum stock price
    min_price: 10                   # Minimum stock price
    
    # Breakout detection
    breakout_lookback_period: 20    # Days to look back for breakouts
    volume_surge_multiplier: 2.0    # Volume must be 2x average
    price_breakout_percentage: 0.02  # 2% price breakout threshold
    
    # Risk management
    stop_loss_percentage: 0.08      # 8% stop loss
    profit_target_multiplier: 2.0   # 2:1 reward:risk ratio
    max_hold_days: 10               # Maximum holding period
    
    # Position sizing
    base_position_size: 10000       # Base position size in USD
    volatility_adjustment: true     # Adjust for volatility
    correlation_limit: 0.7          # Max correlation between positions
  
  # Specific sub-strategies
  sub_strategies:
    breakout:
      enabled: true
      weight: 0.4
      min_consolidation_days: 5
      max_consolidation_days: 30
      breakout_volume_multiplier: 1.5
    
    episodic_pivot:
      enabled: true
      weight: 0.3
      pivot_strength: 3
      volume_confirmation: true
      follow_through_required: true
    
    parabolic_short:
      enabled: true
      weight: 0.3
      parabolic_threshold: 0.20     # 20% move in short period
      short_term_days: 3
      volume_exhaustion_signal: true
  
  # Market regime filters
  market_regime_filters:
    bull_market_only: false
    avoid_high_vix: true
    vix_threshold: 30
    market_correlation_check: true
    
  # Screening criteria
  screening:
    fundamental_filters:
      min_revenue_growth: 0.15      # 15% revenue growth
      max_debt_to_equity: 0.5       # 50% max D/E ratio
      positive_earnings: false      # Growth stocks may not have earnings
    
    technical_filters:
      above_moving_average: [20, 50] # Must be above 20 and 50 day MA
      rsi_range: [30, 70]           # RSI between 30-70
      relative_strength: 0.7        # Top 30% relative strength

mean_reversion:
  description: "Mean reversion strategy for oversold conditions"
  enabled: false
  
  parameters:
    oversold_threshold: 30          # RSI threshold
    profit_target: 0.05            # 5% profit target
    stop_loss: 0.03                # 3% stop loss
    hold_period_max: 5             # Max 5 days

pairs_trading:
  description: "Statistical arbitrage pairs trading"
  enabled: false
  
  parameters:
    correlation_threshold: 0.8      # Minimum correlation
    cointegration_p_value: 0.05    # Statistical significance
    entry_z_score: 2.0             # Entry threshold
    exit_z_score: 0.5              # Exit threshold
    lookback_period: 252           # 1 year lookback

# Global strategy settings
global_strategy_settings:
  max_strategies_per_symbol: 1
  strategy_allocation_method: "equal_weight"  # or "risk_parity", "custom"
  rebalance_frequency: "daily"
  
  # Risk limits per strategy
  risk_limits:
    max_portfolio_allocation: 0.20  # 20% max per strategy
    max_drawdown_limit: 0.15       # 15% max drawdown
    var_limit: 0.05                # 5% VaR limit
    
  # Performance requirements
  performance_thresholds:
    min_sharpe_ratio: 1.0
    min_win_rate: 0.45            # 45% minimum win rate
    max_correlation_with_market: 0.8
    
# Strategy ensemble settings
ensemble:
  enabled: true
  combination_method: "weighted_average"
  
  # Individual strategy weights
  strategy_weights:
    qullamaggie: 0.7
    mean_reversion: 0.2
    pairs_trading: 0.1
  
  # Dynamic weight adjustment
  dynamic_weighting:
    enabled: true
    performance_lookback: 30       # Days to look back for performance
    adjustment_frequency: 7        # Adjust weekly
    max_weight_change: 0.1         # Max 10% weight change per adjustment